services:
  home-library-service:
    container_name: nestapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    environment:
      DB_TYPE: postgres
      DB_USERNAME: postgres
      DB_HOST: db # Host should be the name of the db service
      DB_DATABASE: postgres
      DB_PORT: 5432
      DB_PASSWORD: postgres
      JWT_SECRET_KEY: secret123123
      JWT_SECRET_REFRESH_KEY: secret123123
      TOKEN_EXPIRE_TIME: 1h
      TOKEN_REFRESH_EXPIRE_TIME=: 4h
      PORT: 4000

    depends_on:
      - db
    networks:
      - my-network # Explicitly define the network

  db:
    container_name: db
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - my-network # Use the same network as the app

volumes:
  pgdata:

networks:
  my-network:
    driver: bridge # Use a custom bridge network for communication
